task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 343
  crop: 300
  data_layout: NHWC
  reverse_channels: false
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: tflitert
  input_optimization: false
  input_data_layout: NHWC
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.007812
  - 0.007812
  - 0.007812
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: efficientnet-lite4-fp32.tflite
  model_id: cl-0140
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_top1%: 81.5
  model_shortlist: 40
  compact_name: efficientNet-lite4
  shortlisted: true
