
common:
    target_module: 'vision'
    task_type: 'detection'
    target_device: 'TDA4VM'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_download: True #False #True
    dataset_reload: True #False #True
    # max_num_files: [750, 250] #None

    # Object Detection Dataset Examples:
    # -------------------------------------
    # Example 1, (known datasets): 'widerface_detection', 'pascal_voc0712', 'coco_detection', 'udacity_selfdriving', 'tomato_detection', 'tiscapes2017_driving'
    # dataset_name: widerface_detection
    # -------------------------------------
    # Example 2, give a dataset name and input_data_path.
    # input_data_path could be a zip file, tar file or folder
    # for input_data_path these are provided in this repository as examples:
    # './data/examples/datasets/tiscapes2017_driving.zip', './data/examples/datasets/animal_detection.zip'
    # -------------------------------------
    dataset_name: tiscapes2017_driving
    input_data_path: './data/examples/datasets/tiscapes2017_driving.zip'

training:
    # enable/disable training
    enable: True #False

    # Object Detection model chosen can be changed here if needed
    # SSD: #'ssd_mobilenetv2_fpn_lite_mmdet' 'ssd_regnetx_800mf_fpn_bgr_lite_mmdet' #'ssd_regnetx_1p6gf_fpn_bgr_lite_mmdet'
    # YOLOX:'yolox_nano_lite_mmdet', 'yolox_tiny_lite_mmdet', 'yolox_s_lite_mmdet', 'yolox_m_lite_mmdet'
    model_key: 'yolox_s_lite_mmdet'

    training_epochs: 30 #10
    # batch_size: 8 #32
    # learning_rate: 0.005
    num_gpus: 0 #0 #1 #4

compilation:
    # enable/disable compilation
    enable: True #False
    tensor_bits: 8 #16 #32
