
common:
    ai_backend_name: 'vision'
    task_type: 'classification'
    target_device: 'TDA4VM'

dataset:
    # enable/disable dataset loading
    enable: True #False

    annotation_prefix: 'labels'
    dataset_download: False #True
    dataset_reload: True #False
    # max_num_files: [1000, 250] #None

    # Image Classification Dataset Examples:
    # dataset (builtin datasets): 'oxford_flowers102'
    # datset (dataset path examples): './data/labelling/animal_classification.zip'
    dataset_name: './data/examples/datasets/animal_classification.zip'

training:
    # enable/disable training
    enable: True #False

    # Image Classification model chosen can be changed here if needed
    # #'mobilenet_v2_lite_tv' #'mobilenet_v3_large_lite_tv' #'mobilenet_v3_small_lite_tv' #'regnet_x_400mf_tv' #'regnet_x_800mf_tv' #'regnet_x_1_6gf_tv'
    model_key: 'regnet_x_800mf_tv'

    training_epochs: 30 #10
    batch_size: 64 #8 #32
    # learning_rate: 0.005
    num_gpus: 0 #0 #1 #4

compilation:
    # enable/disable compilation
    enable: True #False

    # tensor_bits: 8 #8 #16 #32
