task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NCHW
  reverse_channels: true
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 103.53
  - 116.28
  - 123.675
  input_scale:
  - 0.017429
  - 0.017507
  - 0.017125
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: regnetx-200mf.onnx
  model_id: cl-6360
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_top1%: 68.9
  model_shortlist: 1
  compact_name: regNetx-200mf
  shortlisted: true
  recommended: true
