task_type: depth_estimation
dataset_category: nyudepthv2
calibration_dataset: nyudepthv2
input_dataset: nyudepthv2
preprocess:
  resize:
  - 246
  - 246
  crop:
  - 224
  - 224
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 0
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0
  - 0
  - 0
  input_scale:
  - 0.003922
  - 0.003922
  - 0.003922
  runtime_options:
    advanced_options:output_feature_16bit_names_list: 233, 424
    advanced_options:params_16bit_names_list: ''
  model_path: fast-depth.onnx
  model_id: de-7300
  input_details: null
  output_details: null
  num_inputs: 1
postprocess:
  save_output: false
metric: {}
model_info:
  metric_reference: {}
  model_shortlist: 50
  compact_name: depth-est-fast-depth-224x224
  shortlisted: false
