task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NCHW
  reverse_channels: false
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: resnet50_v1_shape.onnx
  model_id: cl-6010
  input_details: null
  output_details: null
  num_inputs: 1
metric:
  label_offset_pred: -1
model_info:
  metric_reference:
    accuracy_top1%: 76.456
  model_shortlist: 30
  compact_name: resNet50V1p5-mlperf-onnx
  shortlisted: true
