task_type: classification
dataset_category: imagenet
calibration_dataset: imagenet
input_dataset: imagenet
postprocess: {}
preprocess:
  resize: 256
  crop: 224
  data_layout: NCHW
  reverse_channels: false
  backend: pil
  interpolation: null
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 123.675
  - 116.28
  - 103.53
  input_scale:
  - 0.017125
  - 0.017507
  - 0.017429
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: resnext50_32x4d_lite_wt-v2_20230920.onnx
  model_id: cl-6550
  input_details: null
  output_details: null
  num_inputs: 1
model_info:
  metric_reference:
    accuracy_top1%: 81.2
  model_shortlist: 100
  compact_name: resNeXt50-32x4d-wtv2-224
  shortlisted: false
