task_type: segmentation
dataset_category: cocoseg21
calibration_dataset: cocoseg21
input_dataset: cocoseg21
preprocess:
  resize:
  - 512
  - 512
  crop:
  - 512
  - 512
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 1
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.015625
  - 0.015625
  - 0.015625
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: deeplabv3_mobilenet_v3_large_lite_512x512_20210527.onnx
  model_id: ss-8730
  input_details: null
  output_details: null
  num_inputs: 1
postprocess:
  save_output: false
model_info:
  metric_reference:
    accuracy_mean_iou%: 60.8
  model_shortlist: 90
  compact_name: deeplabv3-mobv3-lite-large-cocoseg21-512x512
  shortlisted: false
