task_type: segmentation
dataset_category: ti-robokit_semseg_zed1hd
calibration_dataset: ti-robokit_semseg_zed1hd
input_dataset: ti-robokit_semseg_zed1hd
preprocess:
  resize:
  - 432
  - 768
  crop:
  - 432
  - 768
  data_layout: NCHW
  reverse_channels: false
  backend: cv2
  interpolation: 3
  resize_with_pad: false
  pad_color: 0
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 128.0
  - 128.0
  - 128.0
  input_scale:
  - 0.015625
  - 0.015625
  - 0.015625
  runtime_options:
    advanced_options:output_feature_16bit_names_list: ''
    advanced_options:params_16bit_names_list: ''
  model_path: deeplabv3plus_mnetv2_edgeailite_robokit_768x432_qat-p2.onnx
  model_id: ss-7618
  input_details: null
  output_details: null
  num_inputs: 1
postprocess:
  save_output: false
model_info:
  metric_reference:
    accuracy_mean_iou%: 54.1
  model_shortlist: 10
  compact_name: deeplabv3lite-mobv2-qat-robokit-768x432
  shortlisted: true
  recommended: true
