task_type: keypoint_detection
dataset_category: cocokpts
calibration_dataset: cocokpts
input_dataset: cocokpts
postprocess:
  reshape_list:
  - - -1
    - 57
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
  logits_bbox_to_bbox_ls: false
  keypoint: true
  object6dpose: false
preprocess:
  resize: 640
  crop: 640
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  runtime_options:
    advanced_options:output_feature_16bit_names_list: /0/backbone/backbone/stem/stem.0/act/Relu_output_0,
      /0/head/cls_preds.0/Conv_output_0, /0/head/reg_preds.0/Conv_output_0, /0/head/obj_preds.0/Conv_output_0,
      /0/head/kpts_preds.0/Conv_output_0, /0/head/cls_preds.1/Conv_output_0, /0/head/reg_preds.1/Conv_output_0,
      /0/head/obj_preds.1/Conv_output_0, /0/head/kpts_preds.1/Conv_output_0, /0/head/cls_preds.2/Conv_output_0,
      /0/head/reg_preds.2/Conv_output_0, /0/head/obj_preds.2/Conv_output_0, /0/head/kpts_preds.2/Conv_output_0
    advanced_options:params_16bit_names_list: ''
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: yolox_s_pose_ti_lite_640_20220301_model.prototxt
  model_path: yolox_s_pose_ti_lite_640_20220301_model.onnx
  model_id: kd-7060
  input_details: null
  output_details: null
  num_inputs: 1
metric:
  label_offset_pred: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 49.6
  model_shortlist: 10
  compact_name: human-pose-yolox-s-640x640
  shortlisted: true
  recommended: true
