task_type: keypoint_detection
dataset_category: cocokpts
calibration_dataset: cocokpts
input_dataset: cocokpts
postprocess:
  reshape_list:
  - - -1
    - 57
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
  logits_bbox_to_bbox_ls: false
  keypoint: true
  object6dpose: false
preprocess:
  resize: 416
  crop: 416
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  runtime_options:
    advanced_options:output_feature_16bit_names_list: '3'
    advanced_options:params_16bit_names_list: ''
    object_detection:meta_arch_type: 6
  model_path: yoloxpose_tiny_lite_416x416_20240808_model.onnx
  model_id: kd-7070
  input_details: null
  output_details: null
  num_inputs: 1
metric:
  label_offset_pred: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: 47.2
  model_shortlist: 100
